sudo: required
dist: trusty
language: node_js
node_js:
- '4'
deploy:
  provider: heroku
  api_key:
    secure: qfd2foZbWm/HP3LMLLLhi3TIEd8vwIyG1DOmmb6o1AKuCI6qmVcFReN+ALzc58Kc784s4F1ueLSC3ywThv7/u2ayWNaR+RVZC/YyGUr4cCb1tTPkzaWtU/s8N68OKOUuFGYPsfFzxpzcSiYBSDKcebHrW/o3NK7ri/t+UyInoktgUhLDsKlcMKGt9/1TAAYyphVzd2HozgOs9dmR+RhL3P4t1vcsAJuLRVuAmHkYiB2ANjqtMl+YHLP0zKZp2G1ex9x2DNHouPxZZoes13/p3KIAnR2vTx7fY28C2TuJiKDu+Zo/ebdmbNDnDg0QyuJhMH3BNLkHuXKABHXyE1qglgm9E95paqOgjxAhwZN4rscJbn7s/M6tQ7mzxE+cDX+PViQ4Ws5nFtAKUgFcN5JsFL2pFOACp7EdKKHFQ6XriNpNsOlzeb3mKGFrVDzLVLtiLWOI7cZtDJCFaizqeTMXTZWj86jsEsnwpsKDAnt2bYhtYwBGn5PU1hhHDECpY1qFVZdtw0oeZfS1QgtGdxZ7hrCjwgyi5qKlqtLL5wAOdBa0b1M/jcc/iH4c3XUXpqBVPkaIRmIERotuE4UP8gD5DNkfpAT5rCDD0ONHf+HbgYlYHCioKT05lCd+EbSqH9cbrhWvUA1XB6JiqZCHSrtGK2NBBdYQK8nMc7jWLhX92kI=
  app: quiet-springs-40098
  on:
    repo: ether-camp/wallet
